apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dify.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/component: worker
      annotations:
        gke-gcsfuse/volumes: 'true'
        gke-gcsfuse/ephemeral-storage-limit: '1Gi'
    spec:
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      serviceAccountName: {{ include "dify.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: worker
        image: {{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        resources:
          {{- toYaml .Values.worker.resources | nindent 10 }}
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - "sleep 15"
        env:
        {{- include "dify.commonEnvs" . | nindent 8 }}
        {{- range $key, $value := .Values.config }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value := .Values.worker.additionalEnv }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "dify.fullname" . }}-secrets
              key: SECRET_KEY
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "dify.fullname" . }}-secrets
              key: DB_PASSWORD
        - name: PGVECTOR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "dify.fullname" . }}-secrets
              key: PGVECTOR_PASSWORD
        - name: PLUGIN_DAEMON_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "dify.fullname" . }}-secrets
              key: SERVER_KEY
        - name: PLUGIN_DIFY_INNER_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "dify.fullname" . }}-secrets
              key: PLUGIN_DIFY_INNER_API_KEY
        - name: INNER_API_KEY_FOR_PLUGIN
          valueFrom:
            secretKeyRef:
              name: {{ include "dify.fullname" . }}-secrets
              key: INNER_API_KEY_FOR_PLUGIN
        - name: RESEND_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "dify.fullname" . }}-secrets
              key: RESEND_API_KEY
        volumeMounts:
        - name: gcs
          mountPath: /app/logs
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2
        command:
        - "/cloud-sql-proxy"
        - "--address=0.0.0.0"
        - "--port=5432"
        - "{{ .Values.global.project }}:{{ .Values.cloudSqlProxy.region }}:{{ .Values.cloudSqlProxy.instance }}"
        resources:
          {{- toYaml .Values.cloudSqlProxy.resources | nindent 10 }}
      volumes:
      - name: gcs
        csi:
          driver: gcsfuse.csi.storage.gke.io
          readOnly: false
          volumeAttributes:
            bucketName: utaha-dify-worker
            mountOptions: 'implicit-dirs,file-cache:enable-parallel-downloads:true,file-cache:max-size-mb:-1,uid=1000,gid=1000,file-mode=777,dir-mode=766'