apiVersion: v1
kind: Service
metadata:
  name: {{ include "dify.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.containerPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/component: web
