{{- if .Values.pluginDaemon.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dify.fullname" . }}-plugin-daemon-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: plugin-daemon
spec:
  accessModes:
  - {{ .Values.pluginDaemon.persistence.accessMode }}
  storageClassName: {{ .Values.pluginDaemon.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.pluginDaemon.persistence.size }}
{{- end }}
