apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "dify.fullname" . }}-secret-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.global.project }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "dify.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "10m" }}
  secretStoreRef:
    kind: SecretStore
    name: {{ include "dify.fullname" . }}-secret-store
  target:
    name: {{ include "dify.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecret.data | nindent 4 }}