apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dify.fullname" . }}-sandbox-config
  namespace: {{ .Release.Namespace }}
data:
  python-requirements.txt: |
    {{ .Values.sandbox.config.pythonRequirements | indent 4 }}