apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dify.fullname" . }}-sandbox
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: sandbox
spec:
  replicas: {{ .Values.sandbox.replicas }} # ローカルファイルシステムに依存するため、NFSを使わなければ1で固定
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: sandbox
  template:
    metadata:
      labels:
        app.kubernetes.io/component: sandbox
    spec:
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      serviceAccountName: {{ include "dify.serviceAccountName" . }}
      containers:
      - name: sandbox
        image: "{{ .Values.sandbox.image.repository }}:{{ .Values.sandbox.image.tag }}"
        imagePullPolicy: {{ .Values.sandbox.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.sandbox.containerPort }}
          protocol: TCP
        resources:
          {{- toYaml .Values.sandbox.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.sandbox.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.sandbox.readinessProbe | nindent 10 }}
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - "sleep 15"
        env:
        {{- include "dify.commonEnvs" . | nindent 8 }}
        {{- range $key, $value := .Values.config }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value := .Values.sandbox.additionalEnv }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "dify.fullname" . }}-secrets
              key: CODE_EXECUTION_API_KEY
      # volumes:
      # - name: sandbox-storage
      #   {{- if .Values.sandbox.persistence.enabled }}
      #   persistentVolumeClaim:
      #     claimName: {{ include "dify.fullname" . }}-sandbox-pvc
      #   {{- else }}
      #   emptyDir: {}
      #   {{- end }}