{{- if ((.Values.sandbox.hpa.enables)) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "dify.fullname" . }}-sandbox
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "dify.fullname" . }}-sandbox
  minReplicas: {{ .Values.sandbox.hpa.minReplicas }}
  maxReplicas: {{ .Values.sandbox.hpa.maxReplicas }}
  metrics:
  {{- with .Values.sandbox.hpa.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ . }}
  {{- end }}
  {{- with .Values.sandbox.hpa.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ . }}
  {{- end }}
{{- end }}
