apiVersion: v1
kind: Service
metadata:
  name: {{ include "dify.fullname" . }}-sandbox
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: sandbox
spec:
  type: {{ .Values.sandbox.service.type }}
  ports:
  - name: http
    port: {{ .Values.sandbox.service.port }}
    targetPort: {{ .Values.sandbox.containerPort }}
    protocol: TCP
  selector:
    app.kubernetes.io/component: sandbox
