{{- if .Values.playwright.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dify.fullname" . }}-playwright
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: playwright
spec:
  replicas: {{ .Values.playwright.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: playwright
  template:
    metadata:
      labels:
        app.kubernetes.io/component: playwright
    spec:
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      serviceAccountName: {{ include "dify.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: playwright
        image: {{ .Values.playwright.image }}
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        securityContext:
          runAsNonRoot: true
        command: ["/bin/sh", "-c"]
        args:
          - |
            npx -y playwright@1.51.0 run-server --port 3000 --host 0.0.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dify.fullname" . }}-playwright
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: playwright
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/component: playwright
{{- end }}
