{{- if .Values.playwright.mcp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dify.fullname" . }}-playwright-mcp
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: playwright-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: playwright-mcp
  template:
    metadata:
      labels:
        app.kubernetes.io/component: playwright-mcp
    spec:
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      serviceAccountName: {{ include "dify.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: playwright-mcp
        image: mcr.microsoft.com/playwright/mcp:latest
        ports:
        - containerPort: 8931
          name: http
          protocol: TCP
        securityContext:
          runAsNonRoot: true
        args: ["--allowed-hosts", "*", "--headless", "--browser", "chromium", "--no-sandbox", "--host", "0.0.0.0", "--port", "8931"]
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dify.fullname" . }}-playwright-mcp
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: playwright-mcp
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8931
    targetPort: 8931
  selector:
    app.kubernetes.io/component: playwright-mcp
{{- end }}
